version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
