version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  